# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

header-y += auxvec.h
header-y += byteorder.h
header-y += elf.h
header-y += fcntl.h
header-y += hwcap.h
header-y += kvm_para.h
header-y += param.h
header-y += posix_types.h
header-y += ptrace.h
header-y += setup.h
header-y += sigcontext.h
header-y += siginfo.h
header-y += sram.h
header-y += statfs.h
header-y += ucontext.h
header-y += unistd.h
